FROM python:3.11.9-alpine3.20
WORKDIR /app/
COPY client.py /app/
COPY requirements.txt /app/
ENV BIB_HOST '172.17.0.2' 
ENV BIB_PORT 9999
RUN pip install -r requirements.txt
CMD ["python", "-u", "/app/client.py"]
